name: Release Helm Chart

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.1

      - name: Package Helm chart
        run: helm package helm/uptodon

      - name: Upload release assets
        uses: actions/upload-artifact@v3
        with:
          name: uptodon-chart
          path: uptodon-0.1.0.tgz

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload Chart to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: uptodon-0.1.0.tgz
          asset_name: uptodon-${{ github.ref }}.tgz
          asset_content_type: application/gzip
